
stages:
  - stage: Build_CODE
    dependsOn: [Build_INFRA]
    displayName: Prepare/Build assets for deployment
    jobs:
      - template: templates/build-template.yml
        parameters:
          project: $(Project)
          environmentTag: $(EnvironmentTag)
          shrShortcut: $(SharedServiceShortcut)

  - stage: DEV_Deployment_CODE
    displayName: DEV Deployment Code
    dependsOn:
      - Build_CODE
      - DEV_Deployment_INFRA
    condition: and(succeeded(), or(startsWith(variables['Build.SourceBranch'], 'refs/heads/dev'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature'), startsWith(variables['Build.SourceBranch'], 'refs/heads/bugfix')))
    jobs:
      - deployment: Deploy_DEV_CODE
        environment: '$(EnvironmentTag)'
        pool:
          vmImage: windows-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/deployment-template.yml
                  parameters:
                    company: $(Company)
                    project: $(Project)
                    service: $(Service)
                    region: $(Region)
                    rgName: $(rgName)
                    serviceShortcut: $(ServiceShortcut)
                    shrShortcut: $(SharedServiceShortcut)
                    regionShortcut: $(RegionShortcut)
                    environmentTag: $(EnvironmentTag)
                    serviceConnectionId: '${{ variables.ServiceConnectionId }}'
                    subscriptionId: $(SubscriptionId)
                    shrService: $(SharedServiceName)
                    namespaceTag: '$(NamespaceTag)'